import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link  from "next/link";
import Header from "./components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PixelMarket",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">

      
      <body className={inter.className}>
        
        <Header/>

        <nav>
          <Link href="/products"></Link>
        </nav>

        
        
        {children}
      </body>
    </html>
  );
}
